# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/spring_hibernate?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=020684Dkfl!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp